#home page ad size
conf.web: 
  indexAdsSize: 5
#cross menu max depth
  crossMaxDepth: 2
#vertical menu max depth
  verticalMaxDepth: 3
#home page product size
  indexProductSize: 12
#home page news size
  indexNewsSize: 8
#company desc length
  companyLength: 500
  from: ${conf.email.from}
  to: ${conf.email.to}
#generationed static page local path
  htmlPath: ${html.path}
#upload pic local path
  picPath: ${pic.path}
#company config file local path, avoid classes build override
  companyConfigPath: ${companyConfig.path}
#web config file local path, avoid classes build override
  webConfigPath: ${webConfig.path}
#static resources access path
  staticAceessUrl: ${static.accessPath}
#images server
  imagesServer: ${images.server}
#content limit size
  limitSize: ${content.limit.size}

#mybatis
mybatis: 
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  config-location: classpath:mybatis/mybatisConfig.xml

spring:
  application:
    name: szyoy-manage
  datasource:
    druid:
      url: ${jdbc.url}
      username: ${jdbc.username}
      password: ${jdbc.password}
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-active: 8
      pool-prepared-statements: false
      max-open-prepared-statements: -1
      validation-query: select 'x'
      validation-query-timeout: 5
      test-while-idle: true
      filters: stat,wall
      web-stat-filter:
        enabled: true
        urlPattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        urlPattern: "/druid/*"
        resetEnable: false
        loginUsername: admin
        loginPassword: 123456
      aop-patterns: top.zuishare.service.*
  aop:
    proxy-target-class: true
  profiles:
    active: @profiles.active@
  mvc:
    view: 
      prefix: /views/
      suffix: .jsp
  http:
    encoding:
      force: true

# Redis config
  redis:
    database: 0
# Redis服务器地址
    host: localhost
# Redis服务器连接端口
    port: 6380
# Redis服务器连接密码（默认为空）
    password:
# 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 15
# 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
# 连接池中的最大空闲连接
      max-idle: 10
# 连接池中的最小空闲连接
      min-idle: 5
# 连接超时时间（毫秒）
    timeout: 1000
    
kaptcha: 
  border: 
    yesOrNo: "yes"
    color: 105,179,90
  textproducer: 
    font:
      color: blue
      size: 32
    char: 
      length: 4
  image: 
    width: 125
    height: 41
    
#email config  
email: 
  host: ${conf.email.host}
  protocol: ${conf.email.protocol}
  port: ${conf.email.port}
  username: ${conf.email.username}
  password: ${conf.email.password}
  encoding: UTF-8
  mailSmtpAuth: true
  prop: true
  mailSmtpTimeout: 25000
  mailDebug: ${conf.email.debug}

logback:
  back:
    directory: ${logback.back.directory}

#task.executor
task: 
  executor: 
    corePoolSize: 5
    maxPoolSize: 10
    queueCapacity: 25

server: 
  port: 8081
---
spring:
  profiles: win-local
server:
  port: 8082
---
spring:
  profiles: mac-local
server:
  port: 8082
---
spring:
  profiles: prd
server:
  port: 8080

